openapi: 3.0.0
info:
  title: Kanora Server API
  description: A RESTful API for managing music collections
  version: 1.0.0
  contact:
    name: Eightythreeapps
    url: https://github.com/eightythreeapps/kanora-server

servers:
  - url: http://localhost:3000/api/v1
    description: Local development server
  - url: https://api.kanora.app/api/v1
    description: Production server

tags:
  - name: Health
    description: System health check endpoints
  - name: Authentication
    description: User authentication endpoints
  - name: Users
    description: User management endpoints
  - name: Artists
    description: Artist management endpoints
  - name: Albums
    description: Album management endpoints
  - name: Tracks
    description: Track management endpoints
  - name: Playlists
    description: Playlist management endpoints

paths:
  /health:
    get:
      tags:
        - Health
      summary: Check API health
      description: Returns the health status of the API
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          example: Error message

security:
  - bearerAuth: [] 